src/api/urls.py
from django.urls import path, include
from . import views, rand_tools
from django.views.generic import TemplateView

app_name = "api"

urlpatterns = [
    path(
        "rand/int",
        views.rand_tool_view,
        {"tool": rand_tools.random_integer},
        name="rand_int",
    ),
    path(
        "rand/float",
        views.rand_tool_view,
        {"tool": rand_tools.random_float},
        name="rand_float",
    ),
    path(
        "rand/bytes",
        views.rand_tool_view,
        {"tool": rand_tools.random_bytes},
        name="rand_bytes",
    ),
    path(
        "rand/string",
        views.rand_tool_view,
        {"tool": rand_tools.random_string},
        name="rand_string",
    ),
    path(
        "rand/sequence",
        views.rand_tool_view,
        {"tool": rand_tools.random_sequence},
        name="rand_sequence",
    ),
    path(
        "rand/coin",
        views.rand_tool_view,
        {"tool": rand_tools.random_coin},
        name="rand_coin",
    ),
    path(
        "rand/dice",
        views.rand_tool_view,
        {"tool": rand_tools.random_dice},
        name="rand_dice",
    ),
    path(
        "rand/lotto",
        views.rand_tool_view,
        {"tool": rand_tools.random_lotto},
        name="rand_lotto",
    ),
    path(
        "rand/bitmap",
        views.rand_bitmap_view,
        {"tool": rand_tools.random_bitmap},
        name="rand_bitmap",
    ),
    path(
        "rand/color",
        views.rand_tool_view,
        {"tool": rand_tools.random_color},
        name="rand_color",
    ),
    path(
        "rand/bitmap/gray",
        views.rand_bitmap_view,
        {"tool": rand_tools.random_bitmap_gray},
        name="rand_bitmap_gray",
    ),
    path(
        "rand/bitmap/color",
        views.rand_bitmap_view,
        {"tool": rand_tools.random_bitmap_color},
        name="rand_bitmap_color",
    ),
    path(
        "rand/raw",
        views.rand_raw_view,
        {"tool": rand_tools.random_raw},
        name="rand_raw",
    ),
    path("insufficient_points", views.insufficient_points, name="insufficient_points"),
    path("service_unavailable", views.service_unavailable, name="service_unavailable"),
    path(
        "", TemplateView.as_view(template_name="redoc.html"), name="redoc-schema"
    ),
]

src/auth/urls.py
from django.urls import path
from . import views


app_name = 'auth'

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("account/", views.AccountView.as_view(), name="account"),
    path("verify/", views.verify_email, name="verify"),
    path("check-email/", views.check_email, name="check-email"),
    path("change-password/", views.ChangePasswordView.as_view(), name="change-password"),
]

src/webservice/urls.py
from django.contrib import admin
from django.urls import path, include
from trng.views import ws_status
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", include("webapp.urls", namespace="app"), name="app"),
    path("api/", include("api.urls", namespace="api"), name="api"),
    path("auth/", include("auth.urls", namespace="auth"), name="auth"),
    path("status/", ws_status, name="status"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/503.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="container text-danger">
        <h1 class="mt-3 text-center">503: Service Unavailable</h1>
        <div class="container">
            <h2 class="text-center">Please try again later</h2>
            {% for error in errors %}
            <h2 class="text-center">{{ error }}</h2>
            {% endfor %}
        </div>
    </div>
    <div class="container text-center">
        <a href="javascript:history.back()" class="btn btn-primary mt-4">Go Back</a>
    </div>
</div>
{% endblock %}

src/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <div class="container">
        <h2 class="mt-3">About</h2>
        <blockquote class="blockquote">
            <p class="">TRNG Web Service employs advanced algorithms and hardware to generate truly unpredictable
                numbers,
                crucial for
                cryptography, simulations, and gaming applications. With its robust architecture, it ensures
                high-quality random numbers
                that pass stringent statistical tests for randomness. Users can access this service via an intuitive
                web
                interface or
                integrate it seamlessly into their applications through APIs.
            </p>
        </blockquote>
        <p>For my Engineering Thesis, I delved deep into the intricate workings of random number generation,
            exploring various
            methodologies and algorithms. Developing TRNG Web Service was not only a challenging technical
            endeavor
            but also a
            rewarding experience, as it bridges the theoretical foundations of randomness with practical
            applications. Through
            meticulous research and rigorous testing, I aimed to create a reliable tool that contributes to the
            security and
            efficiency of diverse technological domains. TRNG Web Service stands as a testament to my dedication
            to
            advancing the
            field of random number generation and its pivotal role in modern computing.
        </p>
    </div>
    <div class="container">
        <h2 class="mt-3">How does it work?</h2>
        {% load static %}
        <img src="{% static 'img/diagram.webp' %}" alt="Diagram of the system">
        <p>Fig 1. This diagram represents the structure of trng web service.</p>
    </div>

</div>
{% endblock %}

src/templates/check_email.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-3">
    <h2 class="mt-3">Account confirmation</h2>
    <p class="lead">Check your email for confirmation link, to activate your account.</p>
  </div>
{% endblock %}

src/templates/email-verified.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-3">
    <h2 class="mt-3">Email verified</h2>
    <p class="lead">Your account is now active. You can now <a href="{% url 'auth:login' %}">login</a>.</p>
  </div>
{% endblock %}

src/templates/footer.html
<footer class="footer mt-auto">
    <div class="text-center p-3 text-bg-color">
        © 2024 Copyright:
        <a class="text-bg-color" href="https://kacperochnik.eu/">Kacper Akdağ-Ochnik</a>
        | <a class="text-bg-color" href="/privacy-policy">Privacy Policy</a>
        | <a class="text-bg-color" href="/terms-of-service">Terms of Service</a>
    </div>
</footer>

src/templates/header.html
<header>
    <nav class="navbar navbar-expand-sm bg-primary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
                <ul class="navbar-nav mx-auto">
                    <a class="navbar-brand text-white" href="/">TRNG Web Service</a>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/about">About</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                            data-bs-toggle="dropdown">Random</a>
                        <ul class="dropdown-menu">
                            {% for category in categories %}
                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle test" href="#">{{ category }}</a>
                                <ul class="dropdown-menu">
                                    {% for tool in rand_tools %}
                                    {% if tool.category == category %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'app:'|add:tool.path %}">
                                            {{ tool.name }}
                                        </a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/api">API</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/auth/account">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/status">Service status</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form method="post" action="/auth/logout/">
                            {% csrf_token %}
                            <input type="hidden" name="extra_submit_param" value="extra_submit_value">
                            <button class="nav-link text-white" type="submit" name="submit_param" value="submit_value"
                                class="link-button">
                                Logout
                            </button>
                        </form>
                    </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
                            aria-label="Theme mode">
                            <i class="bi bi-circle-half text-white"></i>
                        </a>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#" data-bs-theme-value="dark">Dark</a></li>
                            <li><a class="dropdown-item" href="#" data-bs-theme-value="light">Light</a></li>
                            <li><a class="dropdown-item" href="#" data-bs-theme-value="auto">Auto</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <script>
        $(document).ready(function () {
            $('.dropdown-submenu a.test').on("click", function (e) {
                // Hide all other submenus
                $('.dropdown-submenu a.test').not(this).next('ul').hide();

                // Toggle the current submenu
                $(this).next('ul').toggle();

                e.stopPropagation();
                e.preventDefault();
            });
        });
    </script>
</header>

src/templates/logged_out.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-3">
    <h2 class="mt-3">Logged out</h2>
    <p class="lead">You have been logged out</p>
  </div>
{% endblock %}

src/templates/login.html
{% extends 'base.html' %}

{% load rest_framework %}

{% block content %}
  <div class="container mt-3">
    <div class="container">
      <h2>Welcome visitor!</h2>
      <h4>You have {{ profile.points }} bits to spend.</h4>
    </div>
    <div class="container">
      <h2 class="mt-4 mb-3">Login</h2>
      <p class="lead">Please login to your account</p>
      <div class="container">
        <form action="" method="post" class="form-group d-flex flex-column gap-4">
          {% csrf_token %}
          {% render_form serializer %}
          {% if invalid %}
          <span style="color: red;">Invalid username or password</span>
          {% endif %}
          <div class="d-flex bd-highlight">
            <div class="me-auto bd-highlight">
              <a href="/auth/forgot-password" class="btn disabled">Forgot Password</a>
            </div>
            <div class="bd-highlight">
              <a href="/auth/register/" class="btn btn-primary">Register</a>
            </div>
            <div class="bd-highlight ps-2">
              <input type="submit" value="Login" class="btn btn-success" />
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/templates/privacy_policy.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="mt-3">Privacy Policy</h1>
    <p><strong>Effective Date:</strong> May 31, 2024</p>
    <p>Welcome to trng.kacperochnik.eu (the "Website"). This Privacy Policy explains how we collect, use, disclose, and
        safeguard your information when you visit our Website or use our web services. By accessing or using our
        Website, you agree to the terms of this Privacy Policy.</p>

    <h2>1. Information We Collect</h2>
    <h3>Automatically Collected Information</h3>
    <p>When you visit the Website, we automatically collect certain information about your device, including information
        about your web browser, IP address, time zone, and some of the cookies that are installed on your device.
        Additionally, as you browse the Website, we collect information about the individual web pages or products that
        you view, what websites or search terms referred you to the Website, and information about how you interact with
        the Website.</p>

    <h3>Registration Information</h3>
    <p>If you choose to register on our Website, we collect personal information that you provide to us, including your
        name and email address.</p>

    <h2>2. Use of Your Information</h2>
    <p>We use the information we collect in the following ways:</p>
    <ul>
        <li><strong>To Provide and Improve Our Services:</strong> We use your information to deliver the services you
            request, improve our Website, and enhance your user experience.</li>
        <li><strong>To Communicate with You:</strong> We use your personal information to contact you with newsletters,
            marketing or promotional materials, and other information that may be of interest to you. You may opt-out of
            receiving any, or all, of these communications from us by following the unsubscribe link or instructions
            provided in any email we send.</li>
        <li><strong>To Analyze Website Usage:</strong> We use the information we collect to understand how our Website
            is being used and to make improvements.</li>
        <li><strong>To Protect Our Services:</strong> We use the information to detect, prevent, and address technical
            issues and to monitor and prevent fraud and other security issues.</li>
    </ul>

    <h2>3. Data Encryption and Security</h2>
    <p>We are committed to protecting your personal information. All data collected from users is encrypted using
        industry-standard encryption protocols. We implement a variety of security measures to maintain the safety of
        your personal information when you enter, submit, or access your personal information.</p>

    <h2>4. Disclosure of Your Information</h2>
    <p>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This
        does not include trusted third parties who assist us in operating our Website, conducting our business, or
        servicing you, so long as those parties agree to keep this information confidential. We may also release your
        information when we believe release is appropriate to comply with the law, enforce our site policies, or protect
        ours or others' rights, property, or safety.</p>

    <h2>5. Your Rights</h2>
    <p>You have the right to:</p>
    <ul>
        <li>Access the personal data we hold about you.</li>
        <li>Request that we correct any inaccuracies in your personal data.</li>
        <li>Request that we delete your personal data.</li>
        <li>Object to the processing of your personal data.</li>
        <li>Request the transfer of your personal data to another party.</li>
    </ul>
    <p>To exercise any of these rights, please contact us using the contact information provided below.</p>

    <h2>6. Changes to Our Privacy Policy</h2>
    <p>We may update this Privacy Policy from time to time to reflect changes to our practices or for other operational,
        legal, or regulatory reasons. We will notify you of any changes by posting the new Privacy Policy on this page.
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are
        effective when they are posted on this page.</p>

    <h2>7. Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, please contact us at:</p>
    <p><strong>Email:</strong> <a href="mailto:kacperochnik01@gmail.com">kacperochnik01@gmail.com</a></p>
    <p><strong>Address:</strong><br>
        trng.kacperochnik.eu<br>
        Tadeusza Rejtana 15<br>
        72-507<br>
        Koszalin</p>

    <p>By using this Website, you acknowledge that you have read and understood this Privacy Policy. Thank you for
        visiting trng.kacperochnik.eu.</p>
</div>
{% endblock %}

src/templates/rand_tool_form.html
{% extends "base.html" %}

{% load rest_framework %}

{% block content %}
<div class="container" style="max-width: 600px;">
    <h2 class="mt-3">{{ name }}</h2>
    <p class="lead">{{ description }}</p>
    <div class="">
        <form action="" method="post" class="form-group d-flex flex-column gap-4">
            {% csrf_token %}
            {% render_form serializer %}
            <div class="d-flex justify-content-between">
                <a href="javascript:history.back()" class="btn btn-primary">Go Back</a>
                <input type="submit" value="Submit" class="btn btn-success">
            </div>
        </form>
    </div>
</div>
{% endblock %}

src/templates/redoc.html
<!DOCTYPE html>
<html>
  <head>
    <title>API Documentation</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
    <style>body { margin: 0; padding: 0; }</style>
  </head>
  <body>
    {% load static %}
    <redoc spec-url="{% static 'schema.yaml' %}"></redoc>
    <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
  </body>
</html>

src/templates/register.html
{% extends 'base.html' %}

{% load rest_framework %}

{% block content %}
  <div class="container mt-3">
    <h2 class="mt-3">Register</h2>
    <p class="lead">Please register an account</p>
    <div class="container">
      <form action="/auth/register/" method="post" class="form-group d-flex flex-column gap-4">
        {% csrf_token %}
        {% render_form serializer template_pack='rest_framework/vertical' %}
        <div class="d-flex justify-content-between">
          <a href="javascript:history.back()" class="btn btn-primary">Go Back</a>
          <input type="submit" value="Register" class="btn btn-success" />
        </div>
      </form>
    </div>
  </div>
{% endblock %}

src/templates/tos.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="mt-3">Terms of Service</h1>
    <p><strong>Effective Date:</strong> May 31, 2024</p>
    <p>Welcome to trng.kacperochnik.eu (the "Website"). By accessing or using our Website and services, you agree to
        comply with and be bound by the following terms and conditions (the "Terms of Service"). Please read these terms
        carefully before using our Website.</p>

    <h2>1. Acceptance of Terms</h2>
    <p>By using the Website, you agree to these Terms of Service. If you do not agree to these terms, please do not use
        our Website.</p>

    <h2>2. Changes to Terms</h2>
    <p>We reserve the right to modify these Terms of Service at any time. Any changes will be posted on this page and
        will take effect immediately upon posting. Your continued use of the Website after any such changes constitutes
        your acceptance of the new terms.</p>

    <h2>3. User Responsibilities</h2>
    <p>Users agree to use the Website for lawful purposes only. You are prohibited from:</p>
    <ul>
        <li>Engaging in any activity that violates any local, state, national, or international law or regulation.</li>
        <li>Uploading or transmitting viruses, malware, or any other harmful code.</li>
        <li>Attempting to gain unauthorized access to any part of the Website or its systems.</li>
        <li>Using the Website in any manner that could interfere with, disrupt, or negatively affect other users.</li>
    </ul>

    <h2>4. Account Suspension and Termination</h2>
    <p>We reserve the right to suspend or terminate your account at our discretion, without notice, for conduct that we
        believe violates these Terms of Service or is harmful to other users of the Website, us, or third parties, or
        for any other reason.</p>

    <h2>5. Limitation of Liability</h2>
    <p>To the fullest extent permitted by law, trng.kacperochnik.eu shall not be liable for any indirect, incidental,
        special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or
        indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:</p>
    <ul>
        <li>Your use of or inability to use the Website.</li>
        <li>Any unauthorized access to or use of our servers and/or any personal information stored therein.</li>
        <li>Any interruption or cessation of transmission to or from the Website.</li>
        <li>Any bugs, viruses, trojan horses, or the like that may be transmitted to or through our Website by any third
            party.</li>
        <li>Any errors or omissions in any content or for any loss or damage incurred as a result of the use of any
            content posted, emailed, transmitted, or otherwise made available through the Website.</li>
    </ul>

    <h2>6. Governing Law</h2>
    <p>These Terms of Service and any separate agreements whereby we provide you services shall be governed by and
        construed in accordance with the laws of Poland</p>

    <h2>7. Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, please contact us at:</p>
    <p><strong>Email:</strong> <a href="mailto:kacperochnik01@gmail.com">kacperochnik01@gmail.com</a></p>
    <p><strong>Address:</strong><br>
        trng.kacperochnik.eu<br>
        Tadeusza Rejtana 15<br>
        72-507<br>
        Koszalin</p>

</div>
{% endblock %}

src/templates/ws_status.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2 class="mt-3">
        TRNG STATUS
        {% if online %}
        <span class="text-success"> • Online</span>
        {% else %}
        <span class="text-danger"> • Offline</span>
        {% endif %}
    </h2>
    <h3>
        Random bytes in the buffer: {{ buffer_size }}
    </h3>
</div>
{% endblock %}